# Generated by Django 6.0.5 on 2026-09-29
#
# The durable snapshot table for the versioned tips API: one row per stored tip
# type, keyed by the type itself, with the source envelope, its digest, the
# record version that wrote it, and the instant it was fetched. The single
# CreateModel operation is conventionally reversible, and no data operation, raw
# statement, second model, index, or history table is introduced here.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SnapshotV1',
            fields=[
                ('type_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('payload', models.JSONField()),
                ('payload_sha256', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'alltips_scraper_snapshot_v1',
                'ordering': ('type_key',),
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('schema_version__gte', 1)),
                        name='snapshot_v1_schema_version_gte_1',
                    ),
                ],
            },
        ),
    ]
